import { NextResponse } from "next/server"

export async function GET() {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  // In a real app, this would come from database
  const payrollData = {
    stats: [
      {
        title: "Total Payroll",
        value: "KES 2,450,000",
        change: "+8.2%",
        icon: "DollarSign",
        color: "text-green-400",
        bgColor: "bg-green-500/20",
      },
      {
        title: "Employees",
        value: "24",
        change: "+2",
        icon: "Users",
        color: "text-blue-400",
        bgColor: "bg-blue-500/20",
      },
      {
        title: "Processing Status",
        value: "85%",
        change: "In Progress",
        icon: "TrendingUp",
        color: "text-yellow-400",
        bgColor: "bg-yellow-500/20",
      },
      {
        title: "Statutory Deductions",
        value: "KES 245,000",
        change: "10%",
        icon: "AlertCircle",
        color: "text-purple-400",
        bgColor: "bg-purple-500/20",
      },
    ],
    employees: [
      {
        id: "emp_001",
        name: "John Doe",
        position: "Senior Developer",
        department: "Engineering",
        grossSalary: 120000,
        paye: 18500,
        nssf: 2160,
        nhif: 1700,
        otherDeductions: 5000,
        netSalary: 92640,
        status: "Processed",
        avatar: "JD",
        email: "john.doe@company.com",
        phone: "+254712345678",
      },
      {
        id: "emp_002",
        name: "Sarah Wilson",
        position: "Product Manager",
        department: "Product",
        grossSalary: 150000,
        paye: 25500,
        nssf: 2160,
        nhif: 1700,
        otherDeductions: 3000,
        netSalary: 117640,
        status: "Processed",
        avatar: "SW",
        email: "sarah.wilson@company.com",
        phone: "+254723456789",
      },
      {
        id: "emp_003",
        name: "Mike Johnson",
        position: "Sales Executive",
        department: "Sales",
        grossSalary: 80000,
        paye: 8500,
        nssf: 1440,
        nhif: 1300,
        otherDeductions: 2000,
        netSalary: 66760,
        status: "Pending",
        avatar: "MJ",
        email: "mike.johnson@company.com",
        phone: "+254734567890",
      },
      {
        id: "emp_004",
        name: "Lisa Brown",
        position: "HR Specialist",
        department: "Human Resources",
        grossSalary: 95000,
        paye: 12500,
        nssf: 1710,
        nhif: 1400,
        otherDeductions: 1500,
        netSalary: 77890,
        status: "Processed",
        avatar: "LB",
        email: "lisa.brown@company.com",
        phone: "+254745678901",
      },
      {
        id: "emp_005",
        name: "David Chen",
        position: "Marketing Manager",
        department: "Marketing",
        grossSalary: 110000,
        paye: 16000,
        nssf: 1980,
        nhif: 1600,
        otherDeductions: 2500,
        netSalary: 87920,
        status: "Pending",
        avatar: "DC",
        email: "david.chen@company.com",
        phone: "+254756789012",
      },
    ],
    summary: {
      totalGross: 555000,
      totalPaye: 81000,
      totalNssf: 9450,
      totalNhif: 7700,
      totalOtherDeductions: 14000,
      totalNet: 442850,
    },
  }

  return NextResponse.json(payrollData)
}
